# ╔═ HEADER ═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=══╗
# ║                                                                       ║
# ║    ███╗   ███╗██╗███╗   ██╗██╗     ██████╗██╗  ██╗ █████╗ ████████╗   ║
# ║    ████╗ ████║██║████╗  ██║██║    ██╔═=═=╝██║  ██║██╔═=██╗╚═=██╔═=╝   ║
# ║    ██╔████╔██║██║██╔██╗ ██║██║    ██║     ███████║███████║   ██║      ║
# ║    ██║╚██╔╝██║██║██║╚██╗██║██║    ██║     ██╔═=██║██╔═=██║   ██║      ║
# ║    ██║ ╚═╝ ██║██║██║ ╚████║██║    ╚██████╗██║  ██║██║  ██║   ██║      ║
# ║    ╚═╝     ╚═╝╚═╝╚═╝  ╚═=═╝╚═╝     ╚═=═=═╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝      ║
# ║                                                                       ║
# ║   ╔═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═╗   ║
# ║   ║ A chat format editor plugin made specifically for MiniMessage ║   ║
# ║   ║         Full support for MiniMessage, Placeholder API         ║   ║
# ║   ╚═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═╝   ║
# ╚═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═╝
# ╔═ GITHUB ═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=══╗
# ║                      github.com/Manered/MiniChat                      ║
# ╚═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═╝
# =═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=
# Placeholders:
# 1. <[papi | placeholderapi | placeholder | placeholder-api | placeholder_api]:papi_tag>
#    Requirement: Placeholder API plugin installed on your server.
#    Example: <papi:luckperms_prefix>
# 2. <[player | name | player-name | player_name]>
#    Requirement: None
#    Example: <player>
# 3. <[display | displayname | display-name | display_name]>
#    Requirement: None
#    Example: <displayname>
# 4. <[message | text]>
#    Requirement: None
#    Example: <message>
# =═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=═=

# Default: <papi:luckperms_prefix><white><player>: <message></white>.
# Default Example Chat Message: Admin Manere_: Hi!
format: "<papi:luckperms_prefix><white><player>: <message></white>"

# Command Settings
commands:
  # Settings for the 'minichat' command.
  minichat:
    # Enable or disable the command.
    # Requires a server restart to update.
    enabled: true

    # Message sent when command is executed by console.
    sender_is_console: "<red>Only players can execute this command!"

    # Message sent when the player lacks permission to execute the command.
    no_permission: "<red>Insufficient permissions!"

    # Information displayed when the 'minichat' command is executed without arguments.
    info:
      - "<b><gradient:#ff66c9:#6634ed>MiniChat</gradient></b> <dark_gray>v1.0.0"
      - "<dark_gray>- <white>GitHub: <click:open_url:'https://github.com/Manered/MiniChat'><#d7b0ff>github.com/Manered/MiniChat"
      - "<dark_gray>- <white>MiniMessage: <click:open_url:'https://webui.advntr.dev'><#d7b0ff>webui.advntr.dev"
      - "<dark_gray>- <white>Author: <#d7b0ff>Manere_"

    # Help information displayed when the player executes 'minichat help'.
    help:
      - "<b><gradient:#ff66c9:#6634ed>MiniChat</gradient></b> <white>Help"
      - "<dark_gray>- <white>minichat help<gray>: Shows a chat message with the valid command syntax/arguments."
      - "<dark_gray>- <white>minichat format <gray><<white>format<gray>><gray>: Updates the chat format in-game."
      - "<dark_gray>- <white>minichat reload<gray>: Reloads the configuration file(s)."

    # Confirmation message when the chat format is changed successfully.
    format_changed_successfully: "<#00ff00>Success! Send any chat message in order to preview the format publicly."

    # Message sent when the player runs 'minichat reload' in order to reload this configuration file in-game easily.
    reloaded_successfully: "<#00ff00>Reloaded configuration file(s) successfully!"